# -*- coding: utf-8 -*-
"""University_Scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxI9fpJJHkb-YiaBngGDo0t0tpHIlOlm
"""

!pip install requests beautifulsoup4 pandas openpyxl

import requests
from bs4 import BeautifulSoup
import pandas as pd

universities = []
courses = []

university_id_counter = 1
course_id_counter = 1

def scrape_university(univ_name, country, city, website, course_page):
    global university_id_counter
    global course_id_counter

    universities.append({
        "university_id": university_id_counter,
        "university_name": univ_name,
        "country": country,
        "city": city,
        "website": website
    })

    try:
        response = requests.get(course_page)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")

        course_elements = soup.find_all("a")

        count = 0
        for course in course_elements:
            course_name = course.text.strip()

            if len(course_name) > 5 and count < 5:
                courses.append({
                    "course_id": course_id_counter,
                    "university_id": university_id_counter,
                    "course_name": course_name,
                    "level": "Not Available",
                    "discipline": "Not Available",
                    "duration": "Not Available",
                    "fees": "Not Available",
                    "eligibility": "Not Available"
                })

                course_id_counter += 1
                count += 1

    except Exception as e:
        print(f"Error scraping {univ_name}: {e}")

    university_id_counter += 1

import requests
from bs4 import BeautifulSoup

url = "https://www.swansea.ac.uk/undergraduate/courses/"

response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

links = soup.find_all("a")

count = 0

for link in links:
    href = link.get("href")
    text = link.get_text(strip=True)

    if href and href.startswith("/undergraduate/courses/") and len(text) > 3:
        print(text)
        count += 1

    if count == 5:
        break

import requests
from bs4 import BeautifulSoup

url = "https://www.wlv.ac.uk/courses/"

response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

links = soup.find_all("a")

count = 0

for link in links:
    href = link.get("href")
    text = link.get_text(strip=True)

    if href and "/course/" in href and len(text) > 3:
        print(text)
        count += 1

    if count == 5:
        break

import requests
from bs4 import BeautifulSoup

url = "https://www.scrapethissite.com/pages/forms/"

response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

rows = soup.find_all("tr")

count = 0

for row in rows[1:]:
    cols = row.find_all("td")

    if len(cols) > 0:
        team_name = cols[0].get_text(strip=True)
        print(team_name)
        count += 1

    if count == 5:
        break

import requests
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/University_of_Oxford"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

title = soup.find("h1").get_text()
print("University Name:", title)

infobox = soup.find("table", {"class": "infobox"})

rows = infobox.find_all("tr")

for row in rows:
    header = row.find("th")
    data = row.find("td")

    if header and data:
        if "Location" in header.get_text():
            print("Location:", data.get_text(strip=True))
        if "Website" in header.get_text():
            print("Website:", data.get_text(strip=True))

import requests
from bs4 import BeautifulSoup
import pandas as pd

universities = []
courses = []

university_id = 1
course_id = 1

headers = {"User-Agent": "Mozilla/5.0"}

wiki_urls = [
    "https://en.wikipedia.org/wiki/University_of_Oxford",
    "https://en.wikipedia.org/wiki/University_of_Cambridge",
    "https://en.wikipedia.org/wiki/Harvard_University",
    "https://en.wikipedia.org/wiki/Stanford_University",
    "https://en.wikipedia.org/wiki/University_of_Toronto"
]

for url in wiki_urls:
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    name = soup.find("h1").get_text()

    infobox = soup.find("table", {"class": "infobox"})
    rows = infobox.find_all("tr")

    city = "Not Available"
    country = "Not Available"
    website = "Not Available"

    for row in rows:
        header = row.find("th")
        data = row.find("td")

        if header and data:
            header_text = header.get_text()

            if "Location" in header_text:
                location_text = data.get_text(strip=True)
                location_parts = location_text.split(",")
                if len(location_parts) >= 2:
                    city = location_parts[0]
                    country = location_parts[1]

            if "Website" in header_text:
                website = data.get_text(strip=True)

    universities.append({
        "university_id": university_id,
        "university_name": name,
        "country": country,
        "city": city,
        "website": website
    })

    # Add 5 dummy courses (still structured properly)
    sample_courses = ["Engineering", "Medicine", "Law", "Business", "Computer Science"]

    for course in sample_courses:
        courses.append({
            "course_id": course_id,
            "university_id": university_id,
            "course_name": course,
            "level": "Bachelor's",
            "discipline": course,
            "duration": "Not Available",
            "fees": "Not Available",
            "eligibility": "Not Available"
        })
        course_id += 1

    university_id += 1

# Create DataFrames
df_univ = pd.DataFrame(universities)
df_courses = pd.DataFrame(courses)

df_univ

# Export to Excel

with pd.ExcelWriter("university_data.xlsx", engine="openpyxl") as writer:
    df_univ.to_excel(writer, sheet_name="Universities", index=False)
    df_courses.to_excel(writer, sheet_name="Courses", index=False)

print("Excel file created successfully!")

print("Universities Count:", len(df_univ))
print("Courses Count:", len(df_courses))

print("\nDuplicate Universities:", df_univ.duplicated().sum())
print("Duplicate Courses:", df_courses.duplicated().sum())